setwd("~/Documents/datasciencecoursera/project 1")
datasets <- "household.txt"
fulldata <- read.table(datasets, skip = 1, sep = ";")
names(fulldata) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
shortlist <- subset(fulldata, fulldata$Date=="1/2/2007"|fulldata$Date=="2/2/2007")
shortlist$Date <- as.Date(shortlist$Date, format="%d/%m/%y")
shortlist$Time <- strptime(shortlist$Time, format="%H:%M:%S")
shortlist[1:1440,"Time"] <- format(shortlist[1:1440,"Time"],"2007-02-01 %H:%M:%S")
shortlist[1441:2880,"Time"] <- format(shortlist[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(shortlist$Time,shortlist$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering")
with(shortlist,lines(Time,as.numeric(as.character(Sub_metering_1))))
with(shortlist,lines(Time,as.numeric(as.character(Sub_metering_2)),col = "red"))
with(shortlist,lines(Time,as.numeric(as.character(Sub_metering_3)),col = "blue"))
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1,lwd = 2, col = c("black","red","blue"))
dev.copy(png,file = "plot3.png", width = 480, height = 480, units = "px", bg = "white")
dev.off()